#cloud-config
runcmd:
  - ufw disable
  - apt update && apt install -y mosh 
  - git clone -q "https://github.com/mininet/mininet" /home/mininet
snap:
    commands:
        00: ['install', 'openvswitch-switch']
        01: ['install', 'mininet']
