#cloud-config
runcmd:
  - ufw disable
  - apt update && apt install -y mosh 
  - git clone -q "https://github.com/mininet/mininet" /home/mininet
  - git clone -q "https://github.com/faucetsdn/ryu.git" /home/ryu
  - git clone -q "https://bitbucket.org/sdnhub/ryu-starter-kit" /home/ryu/ryu/app/sdnhub_apps
  - apt install -y openvswitch-switch
  - apt install -y mininet
  - apt install -y  python3-pip
  - /usr/bin/bash /home/mininet/util/install.sh -nfw
  - pip install ryu
  - pip install eventlet==0.30.2
